# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'ArchitectureSampleApp' do
pod 'CommonLib-iOS', :git => 'https://scm.speednet.pl/scm/git/CommonLib-iOS'
end

target 'ArchitectureSampleAppTests' do

end

